PROGMEM const struct melody msp = {
	.delay_func = delay_1000,
	.notes = {
		{ .o=4, .t=Fs, 	.d=quarter },
		{ .o=4, .t=Fs, 	.d=quarter },
		{ .o=4, .t=Ds, 	.d=quarter },
		{ .o=4, .t=Ds, 	.d=quarter },
		{ .o=4, .t=Fs, 	.d=quarter },
		{ .o=4, .t=Fs, 	.d=quarter },
		{ .o=4, .t=Ds, 	.d=quarter },
		{ .o=4, .t=Ds, 	.d=quarter },
		{ .o=4, .t=E, 	.d=quarter },
		{ .o=4, .t=E, 	.d=eighth },
		{ .o=4, .t=Ds, 	.d=eighth },
		{ .o=4, .t=Cs, 	.d=quarter },
		{ .o=4, .t=Fs, 	.d=quarter },
		{ .o=3, .t=B, 	.d=quarter },
		{ .o=3, .t=B, 	.d=quarter },
		{ .o=3, .t=B, 	.d=half },
		{ .t=End },
	},
};
