PROGMEM const struct melody smb = {
	.delay_func = delay_800,
	.notes = {
		{ .o=4, .t=E, 	.d=eighth },
		{ .o=4, .t=E, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=4, .t=E, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=4, .t=C, 	.d=eighth },
		{ .o=4, .t=E, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=4, .t=G, 	.d=eighth },
		{ .t=R, 	.d=quarter, .dots=1 },
		{ .o=3, .t=G, 	.d=eighth },
		{ .t=R, 	.d=quarter, .dots=1 },

		{ .o=4, .t=C, 	.d=eighth },
		{ .t=R, 	.d=quarter },
		{ .o=3, .t=G, 	.d=eighth },
		{ .t=R, 	.d=quarter },
		{ .o=3, .t=E, 	.d=eighth },
		{ .t=R, 	.d=quarter },
		{ .o=3, .t=A, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=3, .t=B, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=3, .t=As, 	.d=eighth },
		{ .o=3, .t=A, 	.d=eighth },
		{ .t=R, 	.d=eighth },

		{ .o=3, .t=G, 	.d=eighth, .dots=1 },
		{ .o=4, .t=E, 	.d=eighth, .dots=1 },
		{ .o=4, .t=G, 	.d=eighth, .dots=1 },
		{ .o=4, .t=A, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=4, .t=F, 	.d=eighth },
		{ .o=4, .t=G, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=4, .t=E, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=4, .t=C, 	.d=eighth },
		{ .o=4, .t=D, 	.d=eighth },
		{ .o=3, .t=B, 	.d=eighth },
		{ .t=R, 	.d=quarter },

		{ .o=4, .t=C, 	.d=eighth },
		{ .t=R, 	.d=quarter },
		{ .o=3, .t=G, 	.d=eighth },
		{ .t=R, 	.d=quarter },
		{ .o=3, .t=E, 	.d=eighth },
		{ .t=R, 	.d=quarter },
		{ .o=3, .t=A, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=3, .t=B, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=3, .t=As, 	.d=eighth },
		{ .o=3, .t=A, 	.d=eighth },
		{ .t=R, 	.d=eighth },

		{ .o=3, .t=G, 	.d=eighth, .dots=1 },
		{ .o=4, .t=E, 	.d=eighth, .dots=1 },
		{ .o=4, .t=G, 	.d=eighth, .dots=1 },
		{ .o=4, .t=A, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=4, .t=F, 	.d=eighth },
		{ .o=4, .t=G, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=4, .t=E, 	.d=eighth },
		{ .t=R, 	.d=eighth },
		{ .o=4, .t=C, 	.d=eighth },
		{ .o=4, .t=D, 	.d=eighth },
		{ .o=3, .t=B, 	.d=eighth },
		{ .t=End },
	},
};
